# Generated by Django 5.0.7 on 2024-07-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('credito', models.IntegerField()),
                ('rubro', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fechanacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=30)),
                ('contacto', models.EmailField(max_length=254)),
                ('hotel', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Presupuestar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('clientedni', models.IntegerField()),
                ('codigotransporte', models.IntegerField()),
                ('codigodestino', models.IntegerField()),
                ('comentario', models.CharField(max_length=30)),
                ('fechaviaje', models.DateField()),
                ('dias', models.IntegerField()),
                ('pasajeros', models.IntegerField()),
                ('potencial', models.BooleanField()),
                ('enviado', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('empresa', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
